name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Move manifest
        run: mv action.yml dist/action.yml

      - id: version
        name: Get version
        run: |
          RAW=v$(cat package.json | grep '"version":' | cut -d '"' -f 4)
          REG=^$(echo $RAW | sed 's/\./\\./g')$
          TAG=$([ -z "$(git tag -l | grep -E $REG)" ] || echo "$RAW")
          echo "::set-output name=tag::$TAG"

      - id: deploy
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: dist
          force_orphan: true
          enable_jekyll: true
          tag_name: ${{ steps.version.outputs.tag }}

      - name: Output
        run: git log dist -1 --pretty=%H
